import '@/colors/globals.scss'
import { Comfortaa } from 'next/font/google'

const font = Comfortaa({ subsets: ['latin'] })

export const metadata = {
  title: 'CV — João Gomes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={font.className}>{children}</body>
    </html>
  )
}
