import '@/styles/globals.scss'
import { Montserrat } from 'next/font/google'

const font = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'CV — João Gomes',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Avatar.png" sizes="any" />
      </head>
      <body className={font.className}>{children}</body>
    </html>
  )
}
